### ISSUE TITLE
Crates Don't Recognize Keys From Kits

### ISSUE THREAD

**Issue by bkGamingYT** [ConnorLinfoot/CratesPlus#493]
Debug ->
https://mcdebug.xyz/cratesplus/share/qYDUtqV5hU
--------------------------------------------------------------------

Here is my issue: I'm creating a kit with a crate key. When I do /kit [example] (example being the kit name), it gives me the kit. In the kit is everything I put in there and the key. The only problem is that the key will not work with the crate. I've noticed that there isn't an indent on the lore of the key...this may be the problem but I am not sure. I've tried to manually re-lore the key to have the indent, but the crate still will not accept the key. By the way, I'm using EssentialsX if that changes anything...

KeyThatWasSpawnedInWithCratesPlus.JPG was a crate key that was spawned in with /crate key bkGaming_YT common

TryingToAddTheIndent.JPG was the key after trying to add an indent in the config

WithoutTryingToAddTheIndent was the key before I tried to add the indent

![keythatwasspawnedinwithcratesplus](https://user-images.githubusercontent.com/33919755/33159159-18a08064-cfd6-11e7-871f-51fd5a2a821c.JPG)
![tryingtoaddtheindent](https://user-images.githubusercontent.com/33919755/33159160-18b21be4-cfd6-11e7-8e2a-30eacf21f9f5.JPG)
![withouttryingtoaddtheindent](https://user-images.githubusercontent.com/33919755/33159161-18c258ce-cfd6-11e7-86c6-7fe39b1659e8.JPG)

**Comment by bkGamingYT** [comment]
Before anyone replies: I've already read the other issues similar to mine and they didn't help. The person that closes them always says to add the gap/indent in the config but I already tried that. I looked at the code to see if there was a certain amount of spaces in the indent and it was just blank. If I leave it blank in the config it doesn't add the indent. I at least have to have 1 space.

**Comment by bkGamingYT** [comment]
I've added &r to it instead of a space and it added the indent again, but the crate didn't take it.

**Comment by bkGamingYT** [comment]
When I place the keys that aren't accepted in the crate, it doesn't place because it is a crate key according to CratesPlus. It's about the crate not accepting the key because of the lore not being identical to the actual key

**Comment by bkGamingYT** [comment]
Lots of people have had this issue but they haven't solved it...

**Comment by bkGamingYT** [comment]
What would be helpful if you could leave a comment with the correct lore 😃

**Comment by bkGamingYT** [comment]
```
kits:
  starter:
    delay: -1
    items:
    - IRON_SWORD 1
    - IRON_AXE 1
    - IRON_PICKAXE 1
    - IRON_SPADE 1
    - COOKED_BEEF 32
    - WOOD 64
    - COBBLESTONE 64
    - TORCH 64
    - IRON_HELMET 1
    - IRON_LEGGINGS 1
    - IRON_CHESTPLATE 1
    - IRON_BOOTS 1
  supermagical:
    delay: 2592000
    items:
    - DIAMOND_SWORD 1 name:&b&k||&r&1&lSuper&5&lMagical&b&k||&r_&bSword damage_all:2 durability:3 knockback:2 fire_aspect:1 loot_bonus_mobs:3
    - BOW 1 name:&b&k||&r&1&lSuper&5&lMagical&b&k||&r_&bBow arrow_knockback:2 arrow_fire:1 durability:3 arrow_infinite:1
    - GOLDEN_APPLE:1 16
    - GOLDEN_APPLE 32
    - DIAMOND_HELMET 1 name:&b&k||&r&1&lSuper&5&lMagical&b&k||&r_&bHelmet protection_environmental:2 protection_fire:1 durability:3 thorns:1
    - DIAMOND_CHESTPLATE 1 name:&b&k||&r&1&lSuper&5&lMagical&b&k||&r_&bChestplate protection_environmental:2 protection_fire:1 durability:3 protection_projectile:2
    - DIAMOND_LEGGINGS 1 name:&b&k||&r&1&lSuper&5&lMagical&b&k||&r_&bLeggings protection_environmental:2 protection_fire:1 durability:3 protection_projectile:2
    - DIAMOND_BOOTS 1 name:&b&k||&r&1&lSuper&5&lMagical&b&k||&r_&bBoots protection_environmental:2 protection_fire:1 durability:3 thorns:1
    - ARROW 1 knockback:3
    - TRIPWIRE_HOOK 1 name:&dRare_Crate_Key lore:&7Right-Click_on_a_"&dRare&7"_crate|&7to_win_an_item!| durability:1
    - EMERALD_BLOCK 1
    - DIAMOND_BLOCK 5
    - PAPER 1 name:&cFly
    - PAPER 1 name:&1&lBOLD_&rNickname
    - PAPER 1 name:&cC&ao&6l&bo&dr&ee&9d_&rNickname
    - PAPER 1 name:&e&oItalic&r_Nickname
    - PAPER 1 name:&7Your_new_prefix:_&b&k||&r&1&lSuper&5&lMagical&b&k||&r
    - SPONGE 2
    - TRIPWIRE_HOOK 1 name:&5Magical_Crate_Key lore:&7Right-Click_on_a_"&5Magical&7"_crate|&7to_win_an_item!| durability:1
    - IRON_BLOCK 5
    - GOLD_BLOCK 10
    - DIAMOND_PICKAXE 1 name:&b&k||&r&1&lSuper&5&lMagical&b&k||&r_&bPickaxe dig_speed:3 durability:3
    - DIAMOND_AXE 1 name:&b&k||&r&1&lSuper&5&lMagical&b&k||&r_&bAxe dig_speed:3 durability:3
    - DIAMOND_SPADE 1 name:&b&k||&r&1&lSuper&5&lMagical&b&k||&r_&bShovel dig_speed:3 durability:3
    - DIAMOND_HOE 1 name:&b&k||&r&1&lSuper&5&lMagical&b&k||&r_&bHoe durability:3 knockback:3
    - PAPER 1 name:&b&l1_FREE_ITEM_FROM_OWNER! lore:6162832
    - 52:99 1 name:&rIron_Golem_Spawner
  magical:
    delay: 2592000
    items:
    - DIAMOND_SWORD 1 damage_all:1 durability:2 knockback:1 loot_bonus_mobs:2
    - BOW 1 arrow_damage:1 arrow_knockback:1 durability:2
    - GOLDEN_APPLE:1 8
    - GOLDEN_APPLE 16
    - DIAMOND_HELMET 1 protection_environmental:2 protection_fire:1 durability:2 protection_projectile:2
    - DIAMOND_CHESTPLATE 1 protection_environmental:1 durability:2 protection_projectile:1 thorns:1
    - DIAMOND_LEGGINGS 1 protection_environmental:1 durability:2 protection_explosions:1 protection_projectile:1
    - DIAMOND_BOOTS 1 protection_environmental:2 protection_fire:1 durability:2 protection_projectile:2
    - ARROW 1 knockback:2
    - TRIPWIRE_HOOK 1 name:&bUncommon_Crate_Key lore:&7Right-Click_on_a_"&bUncommon&7"_crate|&7to_win_an_item!| durability:1
    - PAPER 1 name:&cC&ao&6l&bo&dr&ee&9d_&rNickname
    - PAPER 1 name:&cFly
    - PAPER 1 name:&7Your_new_prefix:_&b&k||&5&lMagical&b&k||&r
    - COAL_BLOCK 5
    - TRIPWIRE_HOOK 1 name:&dRare_Crate_Key lore:&7Right-Click_on_a_"&dRare&7"_crate|&7to_win_an_item!| durability:1
    - EMERALD_BLOCK 1
    - DIAMOND_BLOCK 1
    - IRON_BLOCK 1
    - GOLD_BLOCK 5
    - SPONGE 1
    - DIAMOND_PICKAXE 1 dig_speed:2 durability:2
    - DIAMOND_AXE 1 dig_speed:2 durability:2
    - DIAMOND_SPADE 1 dig_speed:2 durability:2
    - DIAMOND_HOE 1 durability:2 knockback:2
  elite:
    delay: 2592000
    items:
    - DIAMOND_SWORD 1 damage_all:1 loot_bonus_mobs:1 durability:1
    - BOW 1 arrow_damage:1 durability:1 arrow_infinite:1
    - GOLDEN_APPLE:1 4
    - GOLDEN_APPLE 8
    - DIAMOND_HELMET 1 protection_environmental:1 protection_projectile:1 durability:1
    - DIAMOND_CHESTPLATE 1 protection_environmental:1 protection_fire:1 durability:1
    - DIAMOND_LEGGINGS 1 protection_environmental:1 protection_fire:1 durability:1
    - DIAMOND_BOOTS 1 protection_environmental:1 protection_projectile:1 durability:1
    - ARROW 1 knockback:1
    - TRIPWIRE_HOOK 1 name:&aCommon_Crate_Key lore:&7Right-Click_on_a_"&aCommon&7"_crate|&7to_win_an_item!| durability:1
    - TRIPWIRE_HOOK 1 name:&bUncommon_Crate_Key lore:&7Right-Click_on_a_"&bUncommon&7"_crate|&7to_win_an_item!| durability:1
    - GOLD_BLOCK 1
    - IRON_BLOCK 1
    - DIAMOND_BLOCK 1
    - PAPER 1 name:&7Your_new_prefix:_&5Elite
    - DIAMOND_PICKAXE 1 dig_speed:1 durability:1
    - DIAMOND_AXE 1 dig_speed:1 durability:1
    - DIAMOND_SPADE 1 dig_speed:1 durability:1
    - DIAMOND_HOE 1 durability:1 knockback:1
  lite:
    delay: 2592000
    commands: 
    - crate key %player% common 2
    items:
    - DIAMOND_SWORD 1
    - GOLDEN_APPLE:1 1
    - GOLDEN_APPLE 4
    - DIAMOND_HELMET 1
    - DIAMOND_CHESTPLATE 1
    - DIAMOND_LEGGINGS 1
    - DIAMOND_BOOTS 1
    - DIAMOND_PICKAXE 1
    - DIAMOND_AXE 1
    - DIAMOND_HOE 1
    - TRIPWIRE_HOOK 1 name:&aCommon_Crate_Key lore:&7Right-Click_on_a_"&aCommon&7"_crate|&7to_win_an_item!|&r| durability:1
    - DIAMOND_SPADE 1
    - PAPER 1 name:&7Your_new_prefix:_&dLite
    - TRIPWIRE_HOOK 1 name:&aCommon_Crate_Key lore:&7Right-Click_on_a_"&aCommon&7"_crate|&7to_win_an_item!|&r| durability:1
```
