### ISSUE TITLE
"bound must be positive"

### ISSUE THREAD

**Issue by PassTheMayo** [ConnorLinfoot/CratesPlus#589]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

### Debug Info

config.yml:
```yml
# [][][][][][][][][][][][][][][][][][][][][]
#  CratesPlus V4.5.1 Config
# [][][][][][][][][][][][][][][][][][][][][]
# ------------------------------------------
# There are many placeholders that can now be used withing the config and messages file, placeholders are as followed:
# - %name% - Replaces with the players name, Example: "Notch".
# - %displayname% - Replaces with the players display name, Example: "[Owner] Notch".
# - %uuid% - Replaces with the players UUID.
# - %crate% - The crate types name.
# - %prize% - The name of the winning.
# - %percentage% - Percentage of the winning, useful for "Chance Message".
# - %rand;100;500% - Generates a random number between two numbers, example is between 100 and 500.
# ------------------------------------------
# Don't change the config version!

Config Version: 6
Update Checks: true
Update Branch: spigot
Metrics: true
Default Opener: BasicGUI
Default Cooldown: 5
Crate Protection: false
Disable Key Swapping: false
Default Hologram Text:
- '%crate%'
- Right-Click to Open!
- Left-Click to Preview!
Crates:
  Vote:
    Hologram Text:
    - §eVote Crate
    - §7Left click to preview
    - §7Right click to open
    Knockback: 0
    Broadcast: false
    Firework: true
    Preview: true
    Block: CHEST
    Color: YELLOW
    Cooldown: 1
    Hide Percentages: true
    Permission: cratesplus.crate.vote
    Key:
      Item: TRIPWIRE_HOOK
      Name: §e%type% Crate Key
      Enchanted: true
    Winnings:
      '1':
        Type: COMMAND
        Item Type: GOLD_SPADE
        Item Data: 0
        Percentage: 10
        Name: §e100 Claim Blocks
        Amount: 1
        Commands:
        - adjustbonusclaimblocks %name% 100
        - tellraw %name% {"text":"§cCrates §8» §7You won 100 claim blocks!"}
      '2':
        Type: COMMAND
        Item Type: GOLD_SPADE
        Item Data: 0
        Percentage: 5
        Name: §e500 Claim Blocks
        Amount: 1
        Commands:
        - adjustbonusclaimblocks %name% 500
        - tellraw %name% {"text":"§cCrates §8» §7You won 100 claim blocks!"}
      '3':
        Type: COMMAND
        Item Type: COOKED_BEEF
        Item Data: 0
        Percentage: 10
        Name: §e32 Steak
        Amount: 32
        Commands:
        - give %name% steak 32
      '4':
        Type: COMMAND
        Item Type: GOLD_INGOT
        Item Data: 0
        Percentage: 15
        Name: §e15 Gold
        Amount: 15
        Commands:
        - give %name% goldingot 15
      '5':
        Type: COMMAND
        Item Type: IRON_INGOT
        Item Data: 0
        Percentage: 20
        Name: §e20 Iron
        Amount: 20
        Commands:
        - give %name% ironingot 20
      '6':
        Type: COMMAND
        Item Type: SPONGE
        Item Data: 0
        Percentage: 5
        Name: §e4 Sponge
        Amount: 4
        Commands:
        - give %name% sponge 4
      '7':
        Type: COMMAND
        Item Type: EXP_BOTTLE
        Item Data: 0
        Percentage: 5
        Name: §e22 XP Bottles
        Amount: 22
        Commands:
        - give %name% 384 22
      '8':
        Type: COMMAND
        Item Type: ENDER_PEARL
        Item Data: 0
        Percentage: 5
        Name: §e16 Enderpearls
        Amount: 16
        Commands:
        - give %name% enderpearl 16
      '9':
        Type: COMMAND
        Item Type: DIAMOND
        Item Data: 0
        Percentage: 5
        Name: §e3 Diamonds
        Amount: 3
        Commands:
        - give %name% diamond 3
      '10':
        Type: COMMAND
        Item Type: SADDLE
        Item Data: 0
        Percentage: 10
        Name: §e2 Saddles
        Amount: 2
        Commands:
        - give %name% saddle 2
      '11':
        Type: COMMAND
        Item Type: NAME_TAG
        Item Data: 0
        Percentage: 5
        Name: §eNametag
        Amount: 1
        Commands:
        - give %name% nametag 1
      '12':
        Type: COMMAND
        Item Type: TRIPWIRE_HOOK
        Item Data: 0
        Percentage: 5
        Name: §eVote Crate Key
        Amount: 1
        Commands:
        - cratesplus key %name% vote 1
```

data.yml:
```yml
Data Version: 2
Crate Locations:
  vote:
  - world|310|72|321
  - world|313|72|318
```

### Link/paste of stack trace/error (if any)

```java
[17:58:19 WARN]: [CratesPlus] Task #172 for CratesPlus v4.5.1 generated an exception
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_191]
        at plus.crates.Opener.BasicGUIOpener.doOpen(BasicGUIOpener.java:61) ~[?:?]
        at plus.crates.Opener.Opener$1.run(Opener.java:38) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[server.jar:git-Paper-425]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[server.jar:git-Paper-425]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[server.jar:git-Paper-425]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[server.jar:git-Paper-425]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[server.jar:git-Paper-425]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[server.jar:git-Paper-425]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]```

### Actions to reproduce (if known):
All I did was try to open the crate with the key by right clicking it.
